
INSERT INTO GEODB.USERS(ID,COOKIE, USERNAME,"NAME",LASTNAME,EMAIL,IMAGE, PASSWORD, TOKEN, ACTIVE, "ADMIN")
VALUES (DEFAULT,NULL,'rappasta', 'Lorenzo', 'Framba', 'lorenzoframba@gmail.com',NULL,'4613650b16296964685818117f557e57366f92b', NULL, TRUE, TRUE),
       (DEFAULT,NULL,'Molone','Mattia', 'Molon','molon@gmail.com',NULL,'29707645067686736492cf6e16526b6e4245',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'Tommy','Tommaso','Bonomo','tommasoni394@gmail.com',NULL,'4f4d773a0540130176787a4f1574100759521e',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'Remo','Leonardo','Remondini', 'remoromolo@gmail.com',NULL, '3949350913f2c7e1b31e366c602f4e5a313a75',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'Segret','Giorgio','Segalla','giorgionelo@gmail.com',NULL, '3949350913f2c7e1b31e366c602f4e5a313a75',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'Tonna','Marta','Tonnona', 'martinasesso@gmail.com',NULL, '6b887a3f20353200263603f6773cf09336a',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'Tartagirl','Elia','Salame','piselloni@gmail.com',NULL, '272b3357425e263811344c636c401b25407a',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'MMluca','Luca', 'Rossi', 'marione@gmail.com',NULL, '42a497b6c62447415483e173a21175a64666e65',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'ipoap','Nicola','Nicoli', 'naso@gmail.com',NULL, '5b41455d063c7b7e1c7e697a25261c5f7c532780',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'Bottiglia','Marco','Bestioni', 'tomcat@gmail.com',NULL, '0e23557c11275d16585244671730147418524644',NULL, TRUE,FALSE);

INSERT INTO GEODB.CLIST(ID,"NAME", DESCRIPTION, IMAGE )
VALUES  (DEFAULT, 'PRETTY HEALTHY', 'EATING A LOT FOR LITTLE MONEY',NULL),
        (DEFAULT, 'PRETTY UNHEALTHY', 'EATING BADLY FOR LITTLE MONEY',NULL),
        (DEFAULT, 'PRETTY AVERAGE', 'SHYLY EATING ',NULL),
        (DEFAULT, 'PRETTY CHEAP', 'FOR LITTLE MONEY',NULL),
        (DEFAULT, 'KINDA GOOD', 'NOT EATING ENOUGH',NULL),
        (DEFAULT, 'PRETTY BAD', 'I CANNOT EAT MORE',NULL),
        (DEFAULT, 'SORTA BAD', 'I HAVE TO EAT MORE',NULL),
        (DEFAULT, 'KINDA BAD', 'NOT BAD ENOUGH',NULL),
        (DEFAULT, 'PRETTY EXPENSIVE', 'WASTING SHIT ON FOOD',NULL);


INSERT INTO GEODB.CITEM(ID,"NAME",DESCRIPTION, IMAGE)
VALUES  (DEFAULT, 'meat', 'Everything meaty is to be found here', NULL),
        (DEFAULT, 'cheese', 'Here you will fin a list of our cheeses or related to cheese', NULL),
        (DEFAULT, 'vegetable', 'This list contains all the vegetables you need', NULL),
        (DEFAULT, 'fruit', 'This list contains all the fruits we can offer to you', NULL),
        (DEFAULT, 'bread', 'Here you will be able to find specific items related to flour or bread. All of them contain glutine, so be aware', NULL),
        (DEFAULT, 'sauces', 'Everything related to sauces for you', NULL),
        (DEFAULT, 'dessert', 'A full list of our dessert and sweets', NULL),
        (DEFAULT, 'essential', 'Here you can find your essential for being a good cook', NULL),
        (DEFAULT, 'drinks', 'Full list of avaiable drinks within our service', NULL);

INSERT INTO GEODB.USERSANONIMOUS(ID, COOKIE)    
VALUES (DEFAULT, 'cookiediprova');

INSERT INTO GEODB.LIST(ID,USEROWNER, USERANONOWNER, IDCAT, "NAME",DESCRIPTION, IMAGE)
VALUES  (DEFAULT, 1, null, 1,  'BIRTHDAY', 'I just wanted to get the goods for the party, not too much sugar for us',NULL),
        (DEFAULT, 1, null, 1,  'FRIDAY NIGHT', 'As a family, we do celebrate friday-myDAY, in which we like to eat healthy ',NULL),
        (DEFAULT, 2, null, 2, 'GRANDMA', 'Minimalistic for grandma, but still going to reject it due to fat circumstances ',NULL),
        (DEFAULT, 3, null, 3, 'CHEESE', 'Cheesy meal for us, we do like animals but the juicy milk is what we need',NULL),
        (DEFAULT, 4, null, 4, 'PICNIC', 'A bunch of sandwiches with unexplored sauce in it',NULL),
        (DEFAULT, 5, null, 4, 'COLLEGE', 'Providing a good value for money, not really great but who am I to complain? ',NULL),
        (DEFAULT, 6, null, 2, 'WEEKEND', 'We do like to experiment with expensive and rare meal, therefore we prefer to save up for weekends',NULL),
        (DEFAULT, 7, null, 1, 'FATTY', 'There is that time of the year where you just need to appreciate what you have and celebrate, by eating unpriviledged fat food',NULL),
        (DEFAULT, 7, null, 4, 'FRIEND', 'A bunch of cheesy drinks and some snacks. Easy peasy lemon squeezy. Also some beer',NULL),
        (DEFAULT, null, 1, 3, 'LISTA DI PROVA ANONIMA', 'Gotta stay fit to fit in outfit',NULL);
    

INSERT INTO GEODB.ISFRIEND(USR1,USR2)
VALUES  (1,2),
        (2,1),
        (2,3),
        (1,3),
        (3,4),
        (4,5),
        (4,6),
        (6,4),
        (6,7),
        (8,1),
        (1,8),
        (2,6),
        (4,2);

INSERT INTO GEODB.ITEM(IDCAT,ID,"NAME",LOGO, NOTE)
VALUES (1,DEFAULT,'wurstel',DEFAULT,'Almost meaty'),
       (2,DEFAULT,'chicken',DEFAULT,'Cheap meat '),
       (3,DEFAULT,'horse',DEFAULT,'Expensive meat'),
       (1,DEFAULT,'cow',DEFAULT,'Common meat'),
       (1,DEFAULT,'beef',DEFAULT,'Common high-end meat'),
       (1,DEFAULT,'pork',DEFAULT,'Common low-end meat'),
       (1,DEFAULT,'ribs',DEFAULT,'Good with barbecue sauce'),
       (1,DEFAULT,'sausage',DEFAULT,'Ideal with friends'),
       (2,DEFAULT,'caciotta',DEFAULT,'Tropical cheese'),
       (2,DEFAULT,'yogurt',DEFAULT, 'Ideal with Honey'),
       (2,DEFAULT,'cheese',DEFAULT, 'Random cheese'),  
       (3,DEFAULT,'carrot',DEFAULT, 'Veggie'),
       (3,DEFAULT,'pickle',DEFAULT, 'Common veggie'),
       (3,DEFAULT,'salad',DEFAULT, 'Cheap veggie'),
       (3,DEFAULT,'spinach',DEFAULT, 'Common veggie'),
       (3,DEFAULT,'potato',DEFAULT, 'Good with ribs'),
       (3,DEFAULT,'tomato',DEFAULT, 'Good with salad'),
       (4,DEFAULT,'apple',DEFAULT, 'Common for being fit'),
       (4,DEFAULT,'lemon',DEFAULT, 'Juicy yellowy ball'),
       (4,DEFAULT,'orange',DEFAULT, 'Juicy orangy ball'),
       (4,DEFAULT,'mandarin',DEFAULT, 'Juicy orangy small ball'),
       (4,DEFAULT,'pear',DEFAULT, 'Elegant and taste good'),
       (4,DEFAULT,'strawberry',DEFAULT, 'Small and expensive, recommended for girls'),
       (4,DEFAULT,'raspberry',DEFAULT, 'Recommented for cakes'),
       (4,DEFAULT,'banana',DEFAULT, 'Common fruit'),
       (5,DEFAULT,'pizza',DEFAULT, 'Frozen and tasty'),              
       (5,DEFAULT,'breadsticks',DEFAULT, 'Olive Oil recommended'),
       (5,DEFAULT,'bread',DEFAULT, 'Good for Speck'),
       (5,DEFAULT,'ciabatt',DEFAULT,'Tropical bread'),
       (5,DEFAULT,'cracker',DEFAULT, 'Recommended college snack'),
       (5,DEFAULT,'flour',DEFAULT, 'Good for cakes'),
       (5,DEFAULT,'piada',DEFAULT, 'Good with mozzarella'),
       (5,DEFAULT,'piadina',DEFAULT, 'Good with Stracchino'),
       (5,DEFAULT,'burrito',DEFAULT, 'Mexican vibe'),
       (2,DEFAULT,'stracchino',DEFAULT, 'Common cheese'),
       (2,DEFAULT,'mozzarella',DEFAULT, 'Common cheese'),
       (2,DEFAULT,'asiago',DEFAULT, 'Common cheese'),
       (1,DEFAULT,'speck',DEFAULT, 'For sandwiches'),
       (1,DEFAULT,'prosciutto',DEFAULT, 'ideal for piadinals'),
       (5,DEFAULT,'snail',DEFAULT, 'French night'),
       (5,DEFAULT,'screwdriver',DEFAULT, 'DIY'),
       (1,DEFAULT,'steak',DEFAULT, 'We got the meats'),
       (1,DEFAULT,'hamburger',DEFAULT, 'Classic american burger'),
       (2,DEFAULT,'cheeseburger',DEFAULT, 'Cheesy burger'),
       (5,DEFAULT,'fishburger',DEFAULT, 'Hawaian vibe'),
       (1,DEFAULT,'hotdog',DEFAULT, 'American vibe'),
       (5,DEFAULT,'fries',DEFAULT, 'American vibe'),
       (7,DEFAULT,'waffle',DEFAULT, 'For breakfast'),
       (5,DEFAULT,'potatosalad',DEFAULT, 'Healthy'),
       (5,DEFAULT,'chips',DEFAULT, 'Fat Vibe'),
       (1,DEFAULT,'salmon',DEFAULT, 'Fish night'),
       (1,DEFAULT,'sushi',DEFAULT, 'Japanese night'),
       (1,DEFAULT,'sashimi',DEFAULT, 'Japanese night'),
       (5,DEFAULT,'gyoza',DEFAULT, 'Japanese night'),
       (8,DEFAULT,'soup',DEFAULT, 'Thaiwanese night'),
       (5,DEFAULT,'mochi',DEFAULT, 'Vietnamese vibe'),
       (7,DEFAULT,'ramen',DEFAULT, 'Vietnamese vibe'),
       (5,DEFAULT,'yakitori',DEFAULT, 'Japanese vibe'),
       (8,DEFAULT,'curry',DEFAULT, 'English vibe'),
       (5,DEFAULT,'rice',DEFAULT, 'Chinese vibe'),
       (1,DEFAULT,'nem',DEFAULT, 'Chinese vibe'),
       (5,DEFAULT,'noodles',DEFAULT, 'Japanese vibe'),
       (1,DEFAULT,'duck',DEFAULT, 'Real vibe'),
       (6,DEFAULT,'parmigiana',DEFAULT, 'Trapical vibe'),
       (6,DEFAULT,'pesto',DEFAULT, 'Italian vibe'),
       (6,DEFAULT,'carbonara',DEFAULT, 'Ideal for pasta'),
       (5,DEFAULT,'lasagna',DEFAULT, 'Italian vibe'),
       (5,DEFAULT,'linguine',DEFAULT, 'Ideal for Italian vibe'),
       (6,DEFAULT,'ragu',DEFAULT, 'Ideal for pasta'),
       (5,DEFAULT,'risotto',DEFAULT, 'Italian northern vibe'),
       (6,DEFAULT,'marinara',DEFAULT, 'Pizza vibe'),
       (5,DEFAULT,'pepperoni',DEFAULT, 'Pizza vibe'),
       (7,DEFAULT,'tiramisu',DEFAULT, 'Good for desserts'),
       (7,DEFAULT,'souffle',DEFAULT, 'Good for desserts'),
       (2,DEFAULT,'panna',DEFAULT, 'Good for carbonara'),
       (7,DEFAULT,'chocolate',DEFAULT, 'Ideal for cold'),
       (7,DEFAULT,'pie',DEFAULT, 'Cake vibe'),
       (5,DEFAULT,'clafoutis',DEFAULT, 'Good old one'),
       (5,DEFAULT,'naan',DEFAULT, 'Piadina Stile'),
       (5,DEFAULT,'masala',DEFAULT, 'Vietnamese vibe'),
       (3,DEFAULT,'garlic',DEFAULT, 'Primary'),
       (7,DEFAULT,'gelato',DEFAULT, 'Definition of goodness'),
       (7,DEFAULT,'sorbet',DEFAULT, 'Good for dessert'),
       (7,DEFAULT,'cupcakes',DEFAULT, 'Ideal vibe'),
       (7,DEFAULT,'nutella',DEFAULT, 'good Italy'),
       (7,DEFAULT,'pancakes',DEFAULT, 'Great for dessert'),
       (1,DEFAULT,'chops',DEFAULT, 'We got the Meats'),
       (1,DEFAULT,'kebabs',DEFAULT, 'Oriente vibe'),
       (5,DEFAULT,'ravioli',DEFAULT, 'Italian vibe'),
       (5,DEFAULT,'tortilla',DEFAULT, 'Mexican vibe'),
       (2,DEFAULT,'omelette',DEFAULT, 'Requires eggs'),
       (8,DEFAULT,'eggs',DEFAULT, 'Primary essential'),
       (7,DEFAULT,'cookies',DEFAULT, 'Breakfasty'),
       (5,DEFAULT,'macarons',DEFAULT, 'Italian cousine'),
       (1,DEFAULT,'pancetta',DEFAULT, 'Recommended for Carbonara'),
       (8,DEFAULT,'nuts',DEFAULT, 'Simply nuts'),
       (2,DEFAULT,'gorgonzola',DEFAULT, 'Blue Cheese'),
       (8,DEFAULT,'beans',DEFAULT, 'Mexican vibe'),
       (2,DEFAULT,'milk',DEFAULT, 'Milky'),
       (8,DEFAULT,'sugar',DEFAULT, 'Primart essentials'),
       (8,DEFAULT,'salt',DEFAULT, 'Primart essentials'),
       (5,DEFAULT,'bruschetta',DEFAULT, 'Italian With tomatoes'),
       (3,DEFAULT,'aragula',DEFAULT, 'Recommended on Pizza'),
       (9,DEFAULT,'margarita',DEFAULT, 'Drinking night'),
       (9,DEFAULT,'wine',DEFAULT, 'Elegant drink'),
       (9,DEFAULT,'beer',DEFAULT, 'German Vibe night'),
       (4,DEFAULT,'blueberries',DEFAULT, 'Recommended for girls'),
       (2,DEFAULT,'feta',DEFAULT, 'Almost cheese'),
       (5,DEFAULT,'wasabi',DEFAULT, 'Spicy night'),
       (8,DEFAULT,'honey',DEFAULT, 'Raw from beas'),
       (4,DEFAULT,'grapefruit',DEFAULT, 'Recommended for girls'),
       (2,DEFAULT,'soymilk',DEFAULT, 'Recommended for milky girls'),
       (3,DEFAULT,'mushrooms',DEFAULT, 'Recommended for Risotto'),
       (5,DEFAULT,'cumin',DEFAULT, 'Recommended'),
       (5,DEFAULT,'breadcrubs',DEFAULT, 'Ready to be eaten!'),
       (1,DEFAULT,'tartar',DEFAULT, 'Good fillups'),
       (1,DEFAULT,'bard',DEFAULT, 'Barding is goodie'),
       (8,DEFAULT,'seed',DEFAULT, 'Recommended for gardens'),
       (4,DEFAULT,'huckleberries',DEFAULT, 'YES, we do have them'),
       (3,DEFAULT,'olives',DEFAULT, 'recommended in bread'),
       (5,DEFAULT,'octopus',DEFAULT, 'Fishy Tropical vibe'),
       (3,DEFAULT,'cucumber',DEFAULT, 'Tropical food'),
       (3,DEFAULT,'cinnamon',DEFAULT, 'Lana del Rey likes it'),
       (5,DEFAULT,'raisins',DEFAULT, 'Recommended for children'),
       (5,DEFAULT,'pinto',DEFAULT, 'Mexican vibe'),
       (6,DEFAULT,'mustard',DEFAULT, 'Spicy'),
       (6,DEFAULT,'mayo',DEFAULT, 'Recommended for hot dogs'),
       (5,DEFAULT,'walnuts',DEFAULT, 'Not regular nuts'),
       (5,DEFAULT,'spaghetti',DEFAULT, 'Classic '),
       (5,DEFAULT,'ginger',DEFAULT, 'Not the Softdrink'),
       (5,DEFAULT,'marmalade',DEFAULT, 'Optimal for mountain vibes'),
       (1,DEFAULT,'swordfish',DEFAULT, 'Expensive tropical fish, recommended'),
       (8,DEFAULT,'limes',DEFAULT, 'Like lemons, but smaller and green'),
       (8,DEFAULT,'paprika',DEFAULT, 'Definition of spicy'),
       (3,DEFAULT,'eggplant',DEFAULT, 'It has nothing to do with eggs'),
       (3,DEFAULT,'cabbage',DEFAULT, 'Raw salad'),
       (4,DEFAULT,'berry',DEFAULT, 'Small and Goodie'),
       (9,DEFAULT,'vodka',DEFAULT, 'Hardcore nights'),
       (5,DEFAULT,'paella',DEFAULT, 'Spanish vibe'); 


 
INSERT INTO GEODB.COMPOSE(LIST,ITEM,QUANTITY,TAKE)
VALUES (1,1,2,false),
       (1,2,3,false),
       (1,3,1,false),
       (1,4,1,false),
       (1,5,1,false),
       (1,6,1,false),
       (1,7,1,false),
       (2,2,1,false),
       (2,5,1,false),
       (3,10,1,false),
       (3,11,1,false),
       (3,2,1,false),
       (3,1,1,false),
       (4,2,1,false),
       (4,1,3,false),
       (4,3,3,false),
       (4,4,3,false),
       (5,6,3,false),
       (5,1,3,false),
       (5,2,3,false),
       (5,5,2,false),
       (6,3,2,false),
       (6,6,2,false),
       (7,6,2,false),
       (7,1,2,false),
       (8,2,2,false),
       (8,4,2,false),
       (8,5,2,false);

INSERT INTO GEODB.ACCESS(IDUSER, IDLIST)
VALUES(1,1),
      (1,2),
      (2,1),
      (3,1),
      (4,2),
      (1,9),
      (2,3),
      (3,4),
      (4,5),
      (5,6),
      (6,7),
      (7,8),
      (7,9);
      
    

INSERT INTO GEODB.MESSAGE(ID,IDUSER,IDLIST,TEXT,SENDTIME)
VALUES (DEFAULT,1,1,'state studiando web?',CURRENT_TIMESTAMP),
       (DEFAULT,2,1,'no',CURRENT_TIMESTAMP);


INSERT INTO GEODB.ITEMPERMISSION(categoryItemId,categoryListId)
VALUES (1,1),
       (2,1),
       (1,4),
       (3,3);