
INSERT INTO GEODB.USERS(ID,COOKIE, USERNAME,"NAME",LASTNAME,EMAIL,IMAGE, PASSWORD, TOKEN, ACTIVE, "ADMIN")
VALUES (DEFAULT,NULL,'rappasta', 'Lorenzo', 'Framba', 'lorenzoframba@gmail.com',NULL,'4613650b16296964685818117f557e57366f92b', NULL, TRUE, TRUE),
       (DEFAULT,NULL,'Molone','Mattia', 'Molon','molon@gmail.com',NULL,'29707645067686736492cf6e16526b6e4245',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'Tommy','Tommaso','Bonomo','tommasoni394@gmail.com',NULL,'4f4d773a0540130176787a4f1574100759521e',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'Remo','Leonardo','Remondini', 'remoromolo@gmail.com',NULL, '3949350913f2c7e1b31e366c602f4e5a313a75',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'Segret','Giorgio','Segalla','giorgionelo@gmail.com',NULL, '3949350913f2c7e1b31e366c602f4e5a313a75',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'Tonna','Marta','Tonnona', 'martinasesso@gmail.com',NULL, '6b887a3f20353200263603f6773cf09336a',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'Tartagirl','Elia','Salame','piselloni@gmail.com',NULL, '272b3357425e263811344c636c401b25407a',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'MMluca','Luca', 'Rossi', 'marione@gmail.com',NULL, '42a497b6c62447415483e173a21175a64666e65',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'ipoap','Nicola','Nicoli', 'naso@gmail.com',NULL, '5b41455d063c7b7e1c7e697a25261c5f7c532780',NULL, TRUE,FALSE),
       (DEFAULT,NULL,'Bottiglia','Marco','Bestioni', 'tomcat@gmail.com',NULL, '0e23557c11275d16585244671730147418524644',NULL, TRUE,FALSE);

INSERT INTO GEODB.CLIST(ID,"NAME", DESCRIPTION, IMAGE )
VALUES  (DEFAULT, 'PRETTY HEALTHY', 'EATING A LOT FOR LITTLE MONEY',NULL),
        (DEFAULT, 'PRETTY UNHEALTHY', 'EATING BADLY FOR LITTLE MONEY',NULL),
        (DEFAULT, 'PRETTY AVERAGE', 'SHYLY EATING ',NULL),
        (DEFAULT, 'PRETTY CHEAP', 'FOR LITTLE MONEY',NULL),
        (DEFAULT, 'KINDA GOOD', 'NOT EATING ENOUGH',NULL),
        (DEFAULT, 'PRETTY BAD', 'I CANNOT EAT MORE',NULL),
        (DEFAULT, 'SORTA BAD', 'I HAVE TO EAT MORE',NULL),
        (DEFAULT, 'KINDA BAD', 'NOT BAD ENOUGH',NULL),
        (DEFAULT, 'PRETTY EXPENSIVE', 'WASTING SHIT ON FOOD',NULL);


INSERT INTO GEODB.CITEM(ID,"NAME",DESCRIPTION, IMAGE)
VALUES  (DEFAULT, 'Meat', 'Everything meaty is to be found here', NULL),
        (DEFAULT, 'Cheese', 'Here you will fin a list of our cheeses or related to cheese', NULL),
        (DEFAULT, 'Vegetable', 'This list contains all the vegetables you need', NULL),
        (DEFAULT, 'Fruit', 'This list contains all the fruits we can offer to you', NULL),
        (DEFAULT, 'Bread', 'Here you will be able to find specific items related to flour or bread. All of them contain glutine, so be aware', NULL),
        (DEFAULT, 'Sauces', 'Everything related to sauces for you', NULL),
        (DEFAULT, 'Dessert', 'A full list of our dessert and sweets', NULL),
        (DEFAULT, 'Essential', 'Here you can find your essential for being a good cook', NULL),
        (DEFAULT, 'Drinks', 'Full list of avaiable drinks within our service', NULL),
        (DEFAULT, 'Condiments', 'jhk', NULL),
        (DEFAULT, 'Bakery', 'jhk', NULL),
        (DEFAULT, 'Bath and Body', 'jhk', NULL);


INSERT INTO GEODB.USERSANONIMOUS(ID, COOKIE)    
VALUES (DEFAULT, 'cookiediprova');

INSERT INTO GEODB.LIST(ID,USEROWNER, USERANONOWNER, IDCAT, "NAME",DESCRIPTION, IMAGE)
VALUES  (1, 1, null, 1,  'BIRTHDAY', 'I just wanted to get the goods for the party, not too much sugar for us',NULL),
        (2, 1, null, 1,  'FRIDAY NIGHT', 'As a family, we do celebrate friday-myDAY, in which we like to eat healthy ',NULL),
        (3, 2, null, 2, 'GRANDMA', 'Minimalistic for grandma, but still going to reject it due to fat circumstances ',NULL),
        (4, 3, null, 3, 'CHEESE', 'Cheesy meal for us, we do like animals but the juicy milk is what we need',NULL),
        (5, 4, null, 4, 'PICNIC', 'A bunch of sandwiches with unexplored sauce in it',NULL),
        (6, 5, null, 4, 'COLLEGE', 'Providing a good value for money, not really great but who am I to complain? ',NULL),
        (7, 6, null, 2, 'WEEKEND', 'We do like to experiment with expensive and rare meal, therefore we prefer to save up for weekends',NULL),
        (8, 7, null, 1, 'FATTY', 'There is that time of the year where you just need to appreciate what you have and celebrate, by eating unpriviledged fat food',NULL),
        (9, 7, null, 4, 'FRIEND', 'A bunch of cheesy drinks and some snacks. Easy peasy lemon squeezy. Also some beer',NULL),
        (10, null, 1, 3, 'LISTA DI PROVA ANONIMA', 'Gotta stay fit to fit in outfit',NULL);
    

INSERT INTO GEODB.ISFRIEND(USR1,USR2)
VALUES  (1,2),
        (2,3),
        (1,3),
        (3,4),
        (4,5),
        (4,6),
        (6,7),
        (8,1),
        (2,6),
        (4,2);

INSERT INTO GEODB.ITEM(IDCAT,ID,"NAME",LOGO, NOTE)
VALUES (1,DEFAULT,'wurstel',DEFAULT,'This fun and easy dinner or lunch recipe will have everyone including kiddos happy to eat.'),
       (2,DEFAULT,'chicken',DEFAULT,'Cheap meatSwanson Premium White Chunk Chicken Breast is fully cooked and perfect for quick and easy everyday meals and sides. Living up to Swanson s tradition of simple ingredients, our delicious white chunk chicken breast meat has no antibiotics and comes from farm-raised chickens in the USA.'),
       (3,DEFAULT,'horse',DEFAULT,'Expensive meat'),
       (1,DEFAULT,'cow',DEFAULT,'Common meat'),
       (1,DEFAULT,'beef',DEFAULT,'Common high-end meat'),
       (1,DEFAULT,'pork',DEFAULT,'Common low-end meat'),
       (1,DEFAULT,'ribs',DEFAULT,'Good with barbecue sauce'),
       (1,DEFAULT,'sausage',DEFAULT,'Ideal with friends'),
       (2,DEFAULT,'caciotta',DEFAULT,'Tropical cheese'),
       (2,DEFAULT,'yogurt',DEFAULT, 'Ideal with Honey'),
       (2,DEFAULT,'cheese',DEFAULT, 'Random cheese'),  
       (3,DEFAULT,'carrot',DEFAULT, 'Veggie'),
       (3,DEFAULT,'pickle',DEFAULT, 'Common veggie'),
       (3,DEFAULT,'salad',DEFAULT, 'Cheap veggie'),
       (3,DEFAULT,'spinach',DEFAULT, 'Common veggie'),
       (3,DEFAULT,'potato',DEFAULT, 'Good with ribs'),
       (3,DEFAULT,'tomato',DEFAULT, 'Good with salad'),
       (4,DEFAULT,'apple',DEFAULT, 'Common for being fit'),
       (4,DEFAULT,'lemon',DEFAULT, 'Juicy yellowy ball'),
       (4,DEFAULT,'orange',DEFAULT, 'Juicy orangy ball'),
       (4,DEFAULT,'mandarin',DEFAULT, 'Juicy orangy small ball'),
       (4,DEFAULT,'pear',DEFAULT, 'Elegant and taste good'),
       (4,DEFAULT,'strawberry',DEFAULT, 'Small and expensive, recommended for girls'),
       (4,DEFAULT,'raspberry',DEFAULT, 'Recommented for cakes'),
       (4,DEFAULT,'banana',DEFAULT, 'Common fruit'),
       (5,DEFAULT,'pizza',DEFAULT, 'Frozen and tasty'),              
       (5,DEFAULT,'breadsticks',DEFAULT, 'Olive Oil recommended'),
       (5,DEFAULT,'bread',DEFAULT, 'Good for Speck'),
       (5,DEFAULT,'ciabatt',DEFAULT,'Tropical bread'),
       (5,DEFAULT,'cracker',DEFAULT, 'Recommended college snack'),
       (5,DEFAULT,'flour',DEFAULT, 'Good for cakes'),
       (5,DEFAULT,'piada',DEFAULT, 'Good with mozzarella'),
       (5,DEFAULT,'piadina',DEFAULT, 'Good with Stracchino'),
       (5,DEFAULT,'burrito',DEFAULT, 'Mexican vibe'),
       (2,DEFAULT,'stracchino',DEFAULT, 'Common cheese'),
       (2,DEFAULT,'mozzarella',DEFAULT, 'Common cheese'),
       (2,DEFAULT,'asiago',DEFAULT, 'Common cheese'),
       (1,DEFAULT,'speck',DEFAULT, 'For sandwiches'),
       (1,DEFAULT,'prosciutto',DEFAULT, 'ideal for piadinals'),
       (5,DEFAULT,'snail',DEFAULT, 'French night'),
       (5,DEFAULT,'screwdriver',DEFAULT, 'DIY'),
       (1,DEFAULT,'steak',DEFAULT, 'We got the meats'),
       (1,DEFAULT,'hamburger',DEFAULT, 'Classic american burger'),
       (2,DEFAULT,'cheeseburger',DEFAULT, 'Cheesy burger'),
       (5,DEFAULT,'fishburger',DEFAULT, 'Hawaian vibe'),
       (1,DEFAULT,'hotdog',DEFAULT, 'American vibe'),
       (5,DEFAULT,'fries',DEFAULT, 'American vibe'),
       (7,DEFAULT,'waffle',DEFAULT, 'For breakfast'),
       (5,DEFAULT,'potatosalad',DEFAULT, 'Healthy'),
       (5,DEFAULT,'chips',DEFAULT, 'Fat Vibe'),
       (1,DEFAULT,'salmon',DEFAULT, 'Fish night'),
       (1,DEFAULT,'sushi',DEFAULT, 'Japanese night'),
       (1,DEFAULT,'sashimi',DEFAULT, 'Japanese night'),
       (5,DEFAULT,'gyoza',DEFAULT, 'Japanese night'),
       (8,DEFAULT,'soup',DEFAULT, 'Thaiwanese night'),
       (5,DEFAULT,'mochi',DEFAULT, 'Vietnamese vibe'),
       (5,DEFAULT,'yakitori',DEFAULT, 'Japanese vibe'),
       (8,DEFAULT,'curry',DEFAULT, 'English vibe'),
       (5,DEFAULT,'rice',DEFAULT, 'Chinese vibe'),
       (1,DEFAULT,'nem',DEFAULT, 'Chinese vibe'),
       (5,DEFAULT,'noodles',DEFAULT, 'Japanese vibe'),
       (1,DEFAULT,'duck',DEFAULT, 'Real vibe'),
       (6,DEFAULT,'parmigiana',DEFAULT, 'Trapical vibe'),
       (6,DEFAULT,'pesto',DEFAULT, 'Italian vibe'),
       (6,DEFAULT,'carbonara',DEFAULT, 'Ideal for pasta'),
       (5,DEFAULT,'lasagna',DEFAULT, 'Italian vibe'),
       (5,DEFAULT,'linguine',DEFAULT, 'Ideal for Italian vibe'),
       (6,DEFAULT,'ragu',DEFAULT, 'Ideal for pasta'),
       (5,DEFAULT,'risotto',DEFAULT, 'Italian northern vibe'),
       (6,DEFAULT,'marinara',DEFAULT, 'Pizza vibe'),
       (5,DEFAULT,'pepperoni',DEFAULT, 'Pizza vibe'),
       (2,DEFAULT,'panna',DEFAULT, 'Good for carbonara'),
       (5,DEFAULT,'clafoutis',DEFAULT, 'Good old one'),
       (5,DEFAULT,'naan',DEFAULT, 'Piadina Stile'),
       (5,DEFAULT,'masala',DEFAULT, 'Vietnamese vibe'),
       (3,DEFAULT,'garlic',DEFAULT, 'Primary'),
       (1,DEFAULT,'chops',DEFAULT, 'We got the Meats'),
       (1,DEFAULT,'kebabs',DEFAULT, 'Oriente vibe'),
       (5,DEFAULT,'ravioli',DEFAULT, 'Italian vibe'),
       (5,DEFAULT,'tortilla',DEFAULT, 'Mexican vibe'),
       (2,DEFAULT,'omelette',DEFAULT, 'Requires eggs'),
       (8,DEFAULT,'eggs',DEFAULT, 'Primary essential'),  
       (5,DEFAULT,'macarons',DEFAULT, 'Italian cousine'),
       (1,DEFAULT,'pancetta',DEFAULT, 'Recommended for Carbonara'),
       (8,DEFAULT,'nuts',DEFAULT, 'Simply nuts'),
       (2,DEFAULT,'gorgonzola',DEFAULT, 'Blue Cheese'),
       (8,DEFAULT,'beans',DEFAULT, 'Mexican vibe'),
       (2,DEFAULT,'milk',DEFAULT, 'Milky'),
       (8,DEFAULT,'sugar',DEFAULT, 'Primart essentials'),
       (8,DEFAULT,'salt',DEFAULT, 'Primart essentials'),
       (5,DEFAULT,'bruschetta',DEFAULT, 'Italian With tomatoes'),
       (3,DEFAULT,'aragula',DEFAULT, 'Recommended on Pizza'),
       (9,DEFAULT,'margarita',DEFAULT, 'Drinking night'),
       (9,DEFAULT,'wine',DEFAULT, 'Elegant drink'),
       (4,DEFAULT,'blueberries',DEFAULT, 'Recommended for girls'),
       (2,DEFAULT,'feta',DEFAULT, 'Almost cheese'),
       (5,DEFAULT,'wasabi',DEFAULT, 'Spicy night'),
       (8,DEFAULT,'honey',DEFAULT, 'Raw from beas'),
       (4,DEFAULT,'grapefruit',DEFAULT, 'Recommended for girls'),
       (2,DEFAULT,'soymilk',DEFAULT, 'Recommended for milky girls'),
       (3,DEFAULT,'mushrooms',DEFAULT, 'Recommended for Risotto'),
       (5,DEFAULT,'cumin',DEFAULT, 'Recommended'),
       (5,DEFAULT,'breadcrubs',DEFAULT, 'Ready to be eaten!'),
       (1,DEFAULT,'tartar',DEFAULT, 'Good fillups'),
       (1,DEFAULT,'bard',DEFAULT, 'Barding is goodie'),
       (8,DEFAULT,'seed',DEFAULT, 'Recommended for gardens'),
       (4,DEFAULT,'huckleberries',DEFAULT, 'YES, we do have them'),
       (3,DEFAULT,'olives',DEFAULT, 'recommended in bread'),
       (5,DEFAULT,'octopus',DEFAULT, 'Fishy Tropical vibe'),
       (3,DEFAULT,'cucumber',DEFAULT, 'Tropical food'),
       (3,DEFAULT,'cinnamon',DEFAULT, 'Lana del Rey likes it'),
       (5,DEFAULT,'raisins',DEFAULT, 'Recommended for children'),
       (5,DEFAULT,'pinto',DEFAULT, 'Mexican vibe'),
       (6,DEFAULT,'mustard',DEFAULT, 'Spicy'),
       (6,DEFAULT,'mayo',DEFAULT, 'Recommended for hot dogs'),
       (5,DEFAULT,'walnuts',DEFAULT, 'Not regular nuts'),
       (5,DEFAULT,'spaghetti',DEFAULT, 'Classic '),
       (5,DEFAULT,'ginger',DEFAULT, 'Not the Softdrink'),
       (5,DEFAULT,'marmalade',DEFAULT, 'Optimal for mountain vibes'),
       (1,DEFAULT,'swordfish',DEFAULT, 'Expensive tropical fish, recommended'),
       (8,DEFAULT,'limes',DEFAULT, 'Like lemons, but smaller and green'),
       (8,DEFAULT,'paprika',DEFAULT, 'Definition of spicy'),
       (3,DEFAULT,'eggplant',DEFAULT, 'It has nothing to do with eggs'),
       (3,DEFAULT,'cabbage',DEFAULT, 'Raw salad'),
       (4,DEFAULT,'berry',DEFAULT, 'Small and Goodie'),
       (10,DEFAULT,'Reggae Reggae Sauce',DEFAULT, 'Bring the sunshine of the Caribbean to your food with a splash of Levi Roots Mild Reggae Reggae Sauce. A mild and tangy Caribbean BBQ sauce flavoured with allspice and herbs. It has all the taste of a classic Reggae Reggae sauce but without the heat. This versatile sauce is so tasty that it can be used as a marinade for meat or why try a generous splash on the side of your meal? Perfect for dunking your chips or smothering on a burger! '),
       (10,DEFAULT,'Olive Oil Spray',DEFAULT, 'Fry Light Extra Virgin Olive Oil Spray is made using only the best quality Extra Virgin Olive Oil and is ideal for baking, roasting and shallow frying when you want a more subtle olive oil flavouring. This handy spray oil product delivers precisely one calorie per spray, making it the perfect choice if you are calorie counting or just watching your weight generally. This unique and innovative product has won several consumer awards; if you haven’t tried it yet now is your chance.'),
       (10,DEFAULT,'Salad Cream Squeezy',DEFAULT, 'Heinz Squeezy Salad Cream Top Down is a modern take on the original and celebrated Heinz Salad Cream. Unlike the traditional glass bottle, this version comprises of a squeezy bottle with the lid pointing downwards. The major advantage of Heinz Squeezy Salad Cream Top Down is that it is much easier to use – there is no need to spend wasted minutes patting the end of the bottle, even when there is hardly any salad cream left. The salad cream itself is unchanged, offering that instantly recognisable flavour; tangy and more vinegary than mayonnaise, and perfect for adding that certain something to an otherwise bland salad.'),
       (10,DEFAULT,'Piccalilli Pickle',DEFAULT, 'This Piccalilli Pickle is a deliciously fruity and tangy pickle from sauce masters Heinz. It contains an intoxicating mixture of marrow, cauliflower and turmeric as well as various other vegetables and spices. Heinz Piccalilli Pickle is a great accompaniment to a cooked breakfast or ploughman’s lunch. If you have never tried this condiment then give it a go – you won’t be disappointed.'),
       (10,DEFAULT,'Ranch Dressing',DEFAULT, 'Newmans Own Ranch Dressing is a rich and creamy salad dressing, with garlic and parsley, that is the perfect accompaniment to all kinds of salads. A mayonnaise based dressing, ranch dressing is a refreshing way to dress a salad, particularly in the summertime. Suitable for vegetarians and coeliacs. Once opened, store in the fridge and use within four weeks.'),
       (10,DEFAULT,'Sarsons Malt Vinegar',DEFAULT, 'Vinegar is an essential part of so many British favourites. Sprinkle over chips, fried egg, ham or tomatoes to add an acidic edge to lots of classic dishes. This bottle will sate your vinegar needs for a while, and as it is made from plastic, it is unlikely to break if dropped by butter fingers.'),
       (11,DEFAULT,'Pumpkin Seed Bread',DEFAULT, 'Made using traditional artisan skills and techniques, Biona Organic Rye Pumpkin Seed Bread is a delicious alternative to regular bread. Freshly grinding the grains just before baking creates loaves packed with wholegrain goodness. And with pumpkin seeds known for their health benefits, you can enjoy a slice of this delicious bread guilt free.'),
       (11,DEFAULT,'Wraps Wheat',DEFAULT, 'Why choose between wheat and white wraps when you can have both with these wraps from Mission Deli? These extra soft wraps from Mission Deli can be used for all sorts of delicious snacks and are easy to use, hot or cold. Simply fill with your ingredients, roll and voila, a tasty way to combine your favourite flavours! Each pack contains 8 soft, fresh wraps for you to enjoy.'),
       (11,DEFAULT,'Crusty Rolls',DEFAULT, 'Smell the aroma of baking bread in your own kitchen, with Paul Hollywood is Ready To Bake Crusty Rolls. A white bread with added Rye flour, all you need to do with these par baked rolls is pop them in the oven. Have a soft or crusty finish, and enjoy a delicious warm bread roll with plenty of melted butter.'),
       (11,DEFAULT,'Sandwich Thins Brown',DEFAULT, 'Warburtons Brown Sandwich Thins offer a great alternative to regular bread. They can be topped, filled or toasted with whatever takes your fancy to make a satisfying and delicious meal. Wonderfully soft and with only 100 calories each, they make a tasty lunchtime alternative to sandwiches. Each pack contains 6 of these delicious thins. '),
       (11,DEFAULT,'White Danish Bread',DEFAULT, 'Bread is generally a no no when it comes to dieting. But thanks to Warburtons, now you can have your slice and eat it, with this white Danish Weight Watchers bread. As each slice contains only 50 calories, you can enjoy the taste of traditional Warburtons bread, without the side portion of guilt. Baked in a traditional pan, this bread has a lovely soft texture, perfect for sandwiches.'),
       (11,DEFAULT,'Genius Crumpets',DEFAULT, 'Wish your morning crumpets were gluten free? Well now they can be with Genius Crumpets. These delicious crumpets are free from all traces of gluten, so even coeliacs can enjoy them. Serve them toasted with plenty of butter, or even a scraping of Marmite if you fancy. They also taste great topped with cheese!'),
       (12,DEFAULT,'Bath & Body Oil',DEFAULT, 'Do you need a bit of re-balancing in your life? This cheekily-named bath and body oil has been designed to de-stress and relax any woman, even after the most difficult of days! It is sure to become a new favourite, and will give you that moment of luxury and bliss you have been waiting for!'),
       (12,DEFAULT,'Hair & Body Wash',DEFAULT, 'Feel like a Rockstar in but a moment with this incredible Joe Bloggs Rock Star Hair & Body Wash 200ml, a potent and luxuriant 2-in-1 for men. This deeply cleansing and nourishing hair and body gel cleanses and softens skin whilst enveloping you in a head to toe sensory experience, complete with scent notes of citrus, spices and wood accords.'),
       (12,DEFAULT,'Bubble Bath',DEFAULT, 'If you or your little ones love the world of Skylander, then this bubble bath will really hit the high notes! Enjoy thick, foamy bubbles, and make every bathtime a real adventure. You are sure to love it and return to it over and over again.'),
       (12,DEFAULT,'Refreshing Leg Gel',DEFAULT, 'With the onset of age comes many unexpected surprises, including the feeling of heaviness and fatigue in our legs, which can be easily combatted with Decleors Aroma Dynamic Circulagel Refreshing Leg Toning Gel 150ml. This incredible gel boosts the skin surfaces micro-circulation, soothes and energises skin, and leaves legs refreshed and ready to take on the day.'),
       (12,DEFAULT,'Lavender Cologne Stick',DEFAULT, 'Yardley English Lavender Cologne Stick 20ml. For her, from the English Lavender collection'),
       (12,DEFAULT,'Insect Repellent Wipe',DEFAULT, 'Before spending time outdoors, be sure to use MosquitNo Insect Repellent Wipe to help keep nasty bugs at bay. Made with nourishing aloe vera and saltidin, which repels mosquitos and ticks, this wipe can be used multiple times on any area of the body. Provides up to 5 hours of protection on areas of the body likely to be targeted by pests.'),
       (9,DEFAULT,'Mango & Lime',DEFAULT, 'Enjoy a refreshing, tropical beverage with a bottle of Ribena Mango & Lime Ready To Drink. Packed full of the flavour of exotic mangoes and zesty limes, this ready to drink bottle is an exciting twist on the traditional Ribena drink. Make sure your fridge is fully stocked as this fruity drink is best served chilled, or even over ice, for maximum refreshment.'),
       (9,DEFAULT,'Green Cola',DEFAULT, 'There have been many versions of this classic fizzy drink over the ages, but few have earned as much praise as this latest green release. Featuring more natural ingredients than ever before, this is a drink which boasts a fantastic flavour - and a recipe which is kinder to you and the planet. Perfect for a sunny day, great with a meal... it is the latest addition to one of the most iconic brands of all time.'),
       (9,DEFAULT,'Natural Mineral Water',DEFAULT, 'Essential Waitrose Natural Mineral Water Still 6 Pack is the deliciously crisp and refreshing water bottled at the source in Shropshire’s Stretton Valley. This water is filtered through minerals, giving each sip an incredibly natural flavour that is sure to slake any thirst the healthiest way possible. Enjoy chilled or over ice with a squeeze of fresh lemon or lime.'),
       (9,DEFAULT,'Oatly Foamable Barista',DEFAULT, 'Thought only dairy milk could froth? Think again! Oatly Foamable Barista beverage makes it easy for dairy-free drinkers to enjoy cafÃ©-worthy coffees at home. This luscious milk is made from oats and is a lighter and less sweet alternative. To make it foam, simply heat in a container and whirl it about occasionally until it gets nice and puffy.'),
       (9,DEFAULT,'Lemonade',DEFAULT, 'Ben Shaws Cloudy Lemonade is the truly authentic taste of British history. Ben Shaws formed his soft drinks company back in the 1800s, and it has been going strong ever since. Some of you may even be able to remember saving up your empty bottles so that you could return them when the Ben Shaws pop van came around. A young entrepreneur could earn themselves 10p per empty bottle! Today Ben Shaws drinks are still extremely popular, and it is not hard to see why. You really can enjoy a nostalgic trip down memory lane with a can of this Ben Shaws Cloudy Lemonade.'),
       (9,DEFAULT,'Grey Goose Vodka',DEFAULT, 'Grey Goose is renowned for making outstanding Vodka with unparalleled smoothness exceptional taste. Their cellar master makes no compromises when creating this rich and full-bodied spirit. Made from the finest French ingredients: single-origin soft winter wheat and natural spring water. With a naturally rich and full-bodied taste, this luxurious vodka can be enjoyed on the rocks or in a martini. 40% ABV.'),
       (9,DEFAULT,'Crafted Beer',DEFAULT, 'Wychwood Brewery Hobgoblin Beer is a delicious traditional craft ruby beer that is full-bodied and packed with mischievous character. Made with Chocolate and Crystal malts and a blend of Styrian, Goldings and Fuggles hops that delivers a chocolate toffee flavour balanced with moderate bitterness and overall fruity character. Hobgoblin is the perfect beer to drink alongside Steak and Ale Pies, Sausages and Mash, BBQs or for Halloween! 5.2% ABV.'),
       (7,DEFAULT,'Chocolate Mini Rolls',DEFAULT, 'Cadburys are responsible for many of the nation’s favourite chocolates and confectionery; the Cadburys Chocolate Mini Rolls is another great example of what they have to offer. This 10 Pack should be enough to help deal with your chocolate cravings for a while, although it is virtually impossible to eat only one.'),
       (7,DEFAULT,'Assorted Blancmange',DEFAULT, 'Blancmange is one of the oldest desserts around, its origins believed to date back as far as medieval times. Pearce Duffs Assorted Blancmange represents the modern incarnation of this much-loved pudding – simply add milk and sugar and off you go! The pack contains one pint sachets of strawberry, raspberry, chocolate and vanilla flavours, so there’s a flavour for everyone. Easy to make, Pearce Duffs Assorted Blancmange is perfect for serving up at children’s parties.'),
       (7,DEFAULT,'Thorntons Shortcake Bites',DEFAULT, 'Shortcake is a great compromise of a snack as it fulfills the cravings of those who love savoury treats and those with a sweet tooth. Thorntons Shortcake Bites are square bite sized caramel shortcakes that everyone will enjoy. The smooth biscuity base is smothered in a generous helping of delicious caramel and topped with milk chocolate. They are the perfect size for those who fancy a nibble! For more than 100 years, Thorntons has been providing the UK with great chocolate and confectionery using the finest cocoa beans.'),
       (7,DEFAULT,'Cake Sultana n Cherry',DEFAULT, 'The Walkers Genoa Cake Sultana and Cherry is a glazed fruit cake packed full of sultanas and cherries. The extra fruitiness gives it a sweet, refreshing flavour that is somewhat lighter than the traditional fruit cake.'),
       (7,DEFAULT,'Chocolate Teacakes',DEFAULT, 'Tunnock’s Chocolate Teacakes 6 Pack are perfect for sharing – if you want to give any away, that is! A perfect combination of light marshmallow and chocolate, these tasty treats are great at any time of the day and make for a perfect teatime snack! '),
       (7,DEFAULT,'cookies',DEFAULT, 'Breakfasty'),
       (7,DEFAULT,'gelato',DEFAULT, 'Definition of goodness'),
       (7,DEFAULT,'sorbet',DEFAULT, 'Good for dessert'),
       (7,DEFAULT,'cupcakes',DEFAULT, 'Ideal vibe'),
       (7,DEFAULT,'nutella',DEFAULT, 'good Italy'),
       (7,DEFAULT,'pancakes',DEFAULT, 'Great for dessert'),
       (7,DEFAULT,'chocolate',DEFAULT, 'Ideal for cold'),
       (7,DEFAULT,'pie',DEFAULT, 'Cake vibe'),
       (7,DEFAULT,'tiramisu',DEFAULT, 'Good for desserts'),
       (7,DEFAULT,'souffle',DEFAULT, 'Good for desserts'),
       (7,DEFAULT,'ramen',DEFAULT, 'Vietnamese vibe'),
       (5,DEFAULT,'paella',DEFAULT, 'Spanish vibe'); 


 
INSERT INTO GEODB.COMPOSE(LIST,ITEM,QUANTITY,TAKE)
VALUES (1,1,2,false),
       (1,2,3,false),
       (1,3,1,false),
       (1,4,1,false),
       (1,5,1,false),
       (1,6,1,false),
       (1,7,1,false),
       (2,2,1,false),
       (2,5,1,false),
       (3,10,1,false),
       (3,11,1,false),
       (3,2,1,false),
       (3,1,1,false),
       (4,2,1,false),
       (4,1,3,false),
       (4,3,3,false),
       (4,4,3,false),
       (5,6,3,false),
       (5,1,3,false),
       (5,2,3,false),
       (5,5,2,false),
       (6,3,2,false),
       (6,6,2,false),
       (7,6,2,false),
       (7,1,2,false),
       (8,2,2,false),
       (8,4,2,false),
       (8,5,2,false);

INSERT INTO GEODB.ACCESS(IDUSER, IDLIST)
VALUES(1,1),
      (1,2),
      (2,1),
      (3,1),
      (4,2),
      (1,9),
      (2,3),
      (3,4),
      (4,5),
      (5,6),
      (6,7),
      (7,8),
      (7,9);
      
    

INSERT INTO GEODB.MESSAGE(ID,IDUSER,IDLIST,TEXT,SENDTIME)
VALUES (DEFAULT,1,1,'state studiando web?',CURRENT_TIMESTAMP),
       (DEFAULT,2,1,'no',CURRENT_TIMESTAMP);


INSERT INTO GEODB.ITEMPERMISSION(categoryItemId,categoryListId)
VALUES (1,1),
       (2,1),
       (1,4),
       (3,3);